[/]
night-light-enabled=true
night-light-last-coordinates=(50.833333000000003, 4.3333329999999997)
night-light-schedule-from=17.0
night-light-schedule-mode='manual'
night-light-schedule-to=7.0
night-light-temperature=uint32 2800
