[desktop]
computer-icon-visible=false
font='Ubuntu 10'
home-icon-visible=false
network-icon-visible=false
show-desktop-icons=true
show-orphaned-desktop-icons=true
trash-icon-visible=false
volumes-visible=false

[plugins]
disabled-actions=@as []

[preferences]
date-format='informal'
default-folder-viewer='compact-view'
ignore-view-metadata=true
last-server-connect-method=1
never-queue-file-ops=true
show-computer-icon-toolbar=false
show-directory-item-counts='always'
show-hidden-files=true
show-icon-view-icon-toolbar=true
show-image-thumbnails='always'
show-location-entry=false
show-new-folder-icon-toolbar=false

[search]
search-reverse-sort=false
search-sort-column='name'

[sidebar-panels/tree]
show-only-directories=true

[window-state]
geometry='1722x886+656+566'
maximized=false
my-computer-expanded=true
network-expanded=true
side-pane-view='places'
sidebar-bookmark-breakpoint=4
sidebar-width=216
start-with-menu-bar=true
start-with-sidebar=true
start-with-status-bar=true
