[/]
custom-list=['custom0', 'custom1', '__dummy__']
show-desklets=@as []

[custom-keybindings/custom0]
binding=['<Shift><Super>t']
command='ghostty --working-directory="~/Coding/projects" --font-size=9'
name='ghostty'

[custom-keybindings/custom1]
binding=['<Super>t']
command="bash -c 'gnome-terminal --working-directory=\"$HOME/Coding/projects\"'"
name='terminal'

[media-keys]
area-screenshot=['<Shift>Print', '<Super>s']
calculator=['XF86Calculator', '<Super>c']
home=['<Super>e', 'XF86Explorer']

[wm]
toggle-recording=['<Control><Shift><Alt>r', '<Super>r']
